### ISSUE TITLE
Repository Cleanup/Additions

### ISSUE THREAD

**Issue by rolo-r** [Bit-Bangers-UTA/Senior-Design#5]
To make the repository more presentable, there's a few things we can do to clean it up.

### Todo list:

- [ ] Remove unnecessary and unused commented pieces of code
- [ ] Create consistent formatting across projects
- [ ] Add comments to certain parts of code to better help understand it
- [ ] Move PlatformIO projects/libraries that we didn't use to "Archive" or "Unused" sub-directories
- [x] Upload final CAD files we used to this repository
- [ ] Add parts list (e.g. standoffs or hex nuts we used)
- [ ] Add a nicer README.md
- [ ] Think of a more "PG" name for the robot
- [ ] New logo
- [x] Rename the repository

**Comment by rolo-r** [comment]
I've created a "backup-04/11/24" branch to preserve the original state of the repository, just in case something goes wrong
